spring:
  datasource:
    url: jdbc:mysql://bj-cynosdbmysql-grp-qzs817me.sql.tencentcdb.com:27204?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: Zjq123789
  application:
    name: logistics
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0
      rate: 100
  zipkin:
    base-url: http://localhost:9090/
    discovery-client-enabled: false
  cloud:
    stream:
      bindings:
        input:
          destination: twostepsfromjava-cloud-logisticstopic
          content-type: application/json
          group: logisticsGroup
      kafka:
        binder:
          brokers: localhost
          defaultBrokerPort: 9092
          zkNodes: localhost

server:
  port: 8083

mybatis:
  #    config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations:
    classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# eureka配置 客户端配置，注册到服务中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/