spring:
  datasource:
    url: jdbc:mysql://bj-cynosdbmysql-grp-qzs817me.sql.tencentcdb.com:27204?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: Zjq123789
  application:
    name: user

server:
  port: 8081

mybatis:
  #    config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations:
    classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# eureka配置 客户端配置，注册到服务中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/